/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ea580c",
        "primary-container": "#c2410c",
        "on-primary": "#ffffff",
        "on-primary-container": "#fff7ed",
        "primary-fixed": "#ffedd5",
        "primary-fixed-dim": "#fed7aa",
        "on-primary-fixed": "#431407",
        "secondary": "#f97316",
        "secondary-container": "#fb923c",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffedd5",
        "secondary-fixed-dim": "#bec6e0",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#e2e8f0",
        "surface-container-high": "#cbd5e1",
        "surface-container-highest": "#94a3b8",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-tint": "#ea580c",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "outline": "#94a3b8",
        "outline-variant": "#e2e8f0",
        "on-background": "#0f172a",
        "error": "#dc2626",
        "error-container": "#fee2e2",
        "on-error": "#ffffff",
        "on-error-container": "#991b1b",
        "tertiary": "#994100",
        "tertiary-container": "#c05400",
        "tertiary-fixed": "#ffdbca",
        "tertiary-fixed-dim": "#ffb690",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#783200",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#ffb599"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "gutter": "1.25rem",
        "margin": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "code-ticker": ["Plus Jakarta Sans", "monospace"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
