apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: railresolve-ingress
  namespace: railresolve
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: railresolve.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: railresolve-express
                port:
                  number: 5000

          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: railresolve-frontend
                port:
                  number: 80
